[package]
name = "schedule_course"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
dotenv = "0.15.0"
eframe = "0.29.1"
egui = "0.29.1"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
sqlx = { version ="0.8.2", features = ["sqlite"] }
